apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signapse-ingress
  namespace: signapse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: signapse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 3000
    - host: api.signapse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 8000
    - host: docs.signapse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  number: 8000
    - host: registry.signapse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-server
                port:
                  number: 5000
    - host: registry-ui.signapse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-ui
                port:
                  number: 5001
    - host: minio.signapse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
