apiVersion: v1
kind: Namespace
metadata:
  name: signapse
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: signapse-quota
  namespace: signapse
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    persistentvolumeclaims: "5"
