apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: signapse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-server
  namespace: signapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-server
  template:
    metadata:
      labels:
        app: registry-server
    spec:
      containers:
        - name: registry
          image: registry:2.8.2
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
              value: "['*']"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
              value: "[HEAD,GET,OPTIONS,DELETE]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials
              value: "[true]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
              value: "[Authorization,Accept,Cache-Control]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
              value: "[Docker-Content-Digest]"
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry-server
  namespace: signapse
spec:
  selector:
    app: registry-server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
  type: NodePort
