name: Publish to PyPI

on:
  push:
    branches:
      - main
    paths:
      - "notebooks/package/**"
  pull_request:
    branches:
      - main
    paths:
      - "notebooks/package/**"

defaults:
  run:
    working-directory: notebooks/package/

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          pip install uv --disable-pip-version-check --no-color
      - name: Install dependencies
        run: |
          uv sync -q
      - name: Build package
        run: |
          uv build
      - name: Upload to PyPI
        if: github.event_name == 'push'
        run: |
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
