name: Server Linter

on:
  push:
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

defaults:
  run:
    working-directory: server

jobs:
  server-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -q --disable-pip-version-check --no-color

      - name: isort (check)
        run: |
          isort --version
          isort --check-only --diff ./src

      - name: black (check)
        run: |
          black --version
          black --check --diff ./src

      - name: flake8
        run: |
          flake8 ./src

      - name: mypy
        run: |
          mypy ./src
